export const elements = {
  cardTemplate: document.querySelector('#card-template').content,
  placesList: document.querySelector('.places__list'),
  editButton: document.querySelector('.profile__edit-button'),
  addButton: document.querySelector('.profile__add-button'),
  avatarEditButton: document.querySelector('.profile__avatar-edit'),
  editPopup: document.querySelector('.popup_type_edit'),
  addPopup: document.querySelector('.popup_type_new-card'),
  imagePopup: document.querySelector('.popup_type_image'),
  avatarPopup: document.querySelector('.popup_type_avatar'),
  confirmPopup: document.querySelector('.popup_type_confirm'),
  editForm: document.querySelector('form[name="edit-profile"]'),
  addForm: document.querySelector('form[name="new-place"]'),
  avatarForm: document.querySelector('form[name="edit-avatar"]'),
  profileTitle: document.querySelector('.profile__title'),
  profileDescription: document.querySelector('.profile__description'),
  profileImage: document.querySelector('.profile__image'),
  editNameInput: document.querySelector('.popup__input_type_name'),
  editJobInput: document.querySelector('.popup__input_type_description'),
  popupImage: document.querySelector('.popup__image'),
  popupCaption: document.querySelector('.popup__caption'),
  addCardNameInput: document.querySelector('.popup__input_type_card-name'),
  addCardUrlInput: document.querySelector('.popup__input_type_url'),
  avatarUrlInput: document.querySelector('.popup__input_type_avatar-url')
};